Updated lookup tables structure
IMQS/migrations pull request #68
Opened 2021-09-22 07:06 UTC by Katlegow

Hey guys - kindly review for me there.

Thanks.

2021-09-22 07:55 UTC, FritzOnFire requested changes
I think you just need to change the way you add the defaults, and then this should be good.

2021-09-22 07:55 UTC, FritzOnFire commented on migrations/mirror/2021-09-22-add-acive-key-to-lookup-tables.sql
> +ALTER TABLE public."refActual_ExpenditureType" ALTER COLUMN creation_date SET DEFAULT now();
I don't think these defaults work the way you think they work https://www.postgresql.org/docs/10/ddl-alter.html#id-1.5.4.7.9 . I think you rather want to add the default to the `ADD COLUMN` statement.

2021-09-23 08:20 UTC, FritzOnFire approved these changes
LGTM

2021-09-28 07:19 UTC, frankvanrietimqs commented on migrations/mirror/2021-09-22-add-acive-key-to-lookup-tables.sql
> +CREATE UNIQUE INDEX ON "refActual_ExpenditureType" ("guid");
Wowee. I would add some blank lines between tables

2021-09-28 07:19 UTC, frankvanrietimqs commented on migrations/mirror/2021-09-22-add-acive-key-to-lookup-tables.sql
> +CREATE UNIQUE INDEX ON "refBOQ_Unit" ("guid");
For future reference there is no need to quote all lower case identifiers unless they are reserved words.

2021-09-28 07:19 UTC, frankvanrietimqs commented on migrations/mirror/2021-09-22-add-acive-key-to-lookup-tables.sql
> +ALTER TABLE "refBudget_BudgetType" ADD COLUMN "allow_delete" BOOLEAN;
Check the spec, but I am pretty sure allow_delete should default to false

2021-09-28 07:19 UTC, frankvanrietimqs commented on migrations/mirror/2021-09-22-add-acive-key-to-lookup-tables.sql
> +ALTER TABLE public."refActual_ExpenditureType" ADD CONSTRAINT check_chars CHECK (k::text <> ''::text AND k::text ~ '^[\w]*$'::text);
No need to change it now, but I would suggest that in future you group all changes to a given table. With such a large file it is very tedious to have to scroll up and down the whole time

2021-09-28 07:35 UTC, Katlegow commented on migrations/mirror/2021-09-22-add-acive-key-to-lookup-tables.sql
> +ALTER TABLE "refBudget_BudgetType" ADD COLUMN "allow_delete" BOOLEAN;
According to the spec null implied false but it make sense to default it false. Will fix it.

2021-09-28 07:36 UTC, Katlegow commented on migrations/mirror/2021-09-22-add-acive-key-to-lookup-tables.sql
> +ALTER TABLE public."refActual_ExpenditureType" ADD CONSTRAINT check_chars CHECK (k::text <> ''::text AND k::text ~ '^[\w]*$'::text);
I have all the time at the moment so I will just change it now.

2021-09-28 08:12 UTC, closed without merging

2021-09-29 06:10 UTC, FritzOnFire commented on migrations/mirror/2021-09-22-add-acive-key-to-lookup-tables.sql
> +CREATE UNIQUE INDEX ON "refActual_ExpenditureType" ("guid");
Your commenting on auto generated code...